//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_menu
    {
        public string menu_id { get; set; }
        public string menu_name { get; set; }
        public string link { get; set; }
        public string alias { get; set; }
        public string menu_category_id { get; set; }
        public string parent_id { get; set; }
        public string status { get; set; }
        public string authority_user { get; set; }
    
        public virtual p_menu_category p_menu_category { get; set; }
    }
}
