//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_phone()
        {
            this.phone_booking = new HashSet<phone_booking>();
        }
    
        public string phone_id { get; set; }
        public string phone_name { get; set; }
        public string cost { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public string company_id { get; set; }
        public string code_no { get; set; }
        public string phone_category_id { get; set; }
        public string phone_detail_id { get; set; }
    
        public virtual p_company p_company { get; set; }
        public virtual p_phone_category p_phone_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phone_booking> phone_booking { get; set; }
        public virtual p_phone_detail p_phone_detail1 { get; set; }
    }
}
