//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone_booking
    {
        public int id { get; set; }
        public string phone_id { get; set; }
        public Nullable<System.DateTime> date_booking { get; set; }
        public string status { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public string phone_category_id { get; set; }
    
        public virtual p_phone p_phone { get; set; }
        public virtual p_phone_category p_phone_category { get; set; }
    }
}
